<?php

$packages = [
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 1673,
        'days' => 30,
        'package_price' => 50192,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 2231,
        'days' => 30,
        'package_price' => 66922,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Luxury->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 2788,
        'days' => 30,
        'package_price' => 83653,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 1952,
        'days' => 30,
        'package_price' => 58557,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 2510,
        'days' => 30,
        'package_price' => 75287,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Luxury->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 3067,
        'days' => 30,
        'package_price' => 92018,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 1968,
        'days' => 21,
        'package_price' => 41334,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 2624,
        'days' => 21,
        'package_price' => 55112,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Luxury->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 3281,
        'days' => 21,
        'package_price' => 68891,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 2296,
        'days' => 21,
        'package_price' => 48223,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 2952,
        'days' => 21,
        'package_price' => 62001,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Luxury->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 3609,
        'days' => 21,
        'package_price' => 75780,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 2187,
        'days' => 14,
        'package_price' => 30618,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 2916,
        'days' => 14,
        'package_price' => 40824,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Luxury->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 3645,
        'days' => 14,
        'package_price' => 51030,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 2552,
        'days' => 14,
        'package_price' => 35712,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 3281,
        'days' => 14,
        'package_price' => 45927,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Luxury->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 4010,
        'days' => 14,
        'package_price' => 56133,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 2430,
        'days' => 7,
        'package_price' => 17010,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 3240,
        'days' => 7,
        'package_price' => 22680,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Luxury->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 4050,
        'days' => 7,
        'package_price' => 28350,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 2835,
        'days' => 7,
        'package_price' => 19845,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 3645,
        'days' => 7,
        'package_price' => 25515,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 2700,
        'days' => 3,
        'package_price' => 8100,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 3600,
        'days' => 3,
        'package_price' => 10800,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Luxury->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 4500,
        'days' => 3,
        'package_price' => 13500,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 3150,
        'days' => 3,
        'package_price' => 9450,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 4050,
        'days' => 3,
        'package_price' => 12150,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Luxury->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 4950,
        'days' => 3,
        'package_price' => 14850,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 3000,
        'days' => 1,
        'package_price' => 3000,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 4000,
        'days' => 1,
        'package_price' => 4000,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Luxury->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 5000,
        'days' => 1,
        'package_price' => 5000,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 3500,
        'days' => 1,
        'package_price' => 3500,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 4500,
        'days' => 1,
        'package_price' => 4500,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Luxury->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 5500,
        'days' => 1,
        'package_price' => 5500,
        'monthly_price' => null,
    ],
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 1220,
        'days' => 360,
        'package_price' => 439077,
        'monthly_price' => 36590,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 1626,
        'days' => 360,
        'package_price' => 585435,
        'monthly_price' => 48786,
    ],
    [
        'vehicle_category' => VehicleCategory::Luxury->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 2033,
        'days' => 360,
        'package_price' => 731794,
        'monthly_price' => 60983,
    ],
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 1423,
        'days' => 360,
        'package_price' => 512256,
        'monthly_price' => 42688,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 1829,
        'days' => 360,
        'package_price' => 658615,
        'monthly_price' => 54885,
    ],
    [
        'vehicle_category' => VehicleCategory::Luxury->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 2236,
        'days' => 360,
        'package_price' => 804974,
        'monthly_price' => 67081,
    ],
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 1355,
        'days' => 180,
        'package_price' => 243931,
        'monthly_price' => 40655,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 1807,
        'days' => 180,
        'package_price' => 325242,
        'monthly_price' => 54207,
    ],
    [
        'vehicle_category' => VehicleCategory::Luxury->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 2259,
        'days' => 180,
        'package_price' => 406552,
        'monthly_price' => 67759,
    ],
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 1581,
        'days' => 180,
        'package_price' => 284587,
        'monthly_price' => 47431,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 2033,
        'days' => 180,
        'package_price' => 365897,
        'monthly_price' => 60983,
    ],
    [
        'vehicle_category' => VehicleCategory::Luxury->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 2484,
        'days' => 180,
        'package_price' => 447208,
        'monthly_price' => 74535,
    ],
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 1506,
        'days' => 90,
        'package_price' => 135517,
        'monthly_price' => 45172,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 2008,
        'days' => 90,
        'package_price' => 180690,
        'monthly_price' => 60230,
    ],
    [
        'vehicle_category' => VehicleCategory::Luxury->value,
        'vehicle_type' => VehicleType::Sedan->value,
        'price' => 2510,
        'days' => 90,
        'package_price' => 225862,
        'monthly_price' => 75287,
    ],
    [
        'vehicle_category' => VehicleCategory::Economy->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 1757,
        'days' => 90,
        'package_price' => 158104,
        'monthly_price' => 52701,
    ],
    [
        'vehicle_category' => VehicleCategory::Business->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 2259,
        'days' => 90,
        'package_price' => 203276,
        'monthly_price' => 67759,
    ],
    [
        'vehicle_category' => VehicleCategory::Luxury->value,
        'vehicle_type' => VehicleType::Minivan->value,
        'price' => 2761,
        'days' => 90,
        'package_price' => 248449,
        'monthly_price' => 82816,
    ],

];